config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/github-samples/pets-workshop:
      branch: main
      repo: https://github.com/github-samples/pets-workshop
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/github-samples/pets-workshop git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-olivine-numbat.sh
        container: qc.acc_snazzy-cinnamon-monster
  QC.Doc:
    repos:
      github.com/github-samples/pets-workshop find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-orange-coral.sh
        container: qc.doc_fuzzy-red-beaver
      github.com/github-samples/pets-workshop git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-white-chipmunk.sh
        container: qc.doc_goopy-silver-zebra
      github.com/github-samples/pets-workshop markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-sapphire-mule.sh
        container: qc.doc_flabby-chocolate-badger
  QC.Lic:
    repos:
      github.com/github-samples/pets-workshop licensee:
        commands:
        - /usr/bin/env sh .sqa/script.silly-pumpkin-kiwi.sh
        container: qc.lic_squirrely-bronze-octopus
  QC.Sec:
    repos:
      github.com/github-samples/pets-workshop bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-smalt-capybara.sh
        container: qc.sec_nerdy-sangria-rattlesnake
  QC.Sty:
    repos:
      github.com/github-samples/pets-workshop flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-orange-balinese.sh
        container: qc.sty_jumpy-cardinal-greyhound
      github.com/github-samples/pets-workshop hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-green-shark.sh
        container: qc.sty_boozy-taupe-chow
      github.com/github-samples/pets-workshop jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-wheat-gecko.sh
        container: qc.sty_sunny-silver-gibbon
  QC.Uni:
    repos:
      github.com/github-samples/pets-workshop pytest:
        commands:
        - /usr/bin/env sh .sqa/script.silly-cornflower-moorhen.sh
        container: qc.uni_gummy-gamboge-insect
  QC.Ver:
    repos:
      github.com/github-samples/pets-workshop get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-aquamarine-zebra.sh
        container: qc.ver_baggy-azure-monster
timeout: 5400
